//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the dynamic_tutorials package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __dynamic_tutorials__TUTORIALSCONFIG_H__
#define __dynamic_tutorials__TUTORIALSCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace dynamic_tutorials
{
  class TutorialsConfigStatics;

  class TutorialsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(TutorialsConfig &config, const TutorialsConfig &max, const TutorialsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const TutorialsConfig &config1, const TutorialsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, TutorialsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const TutorialsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, TutorialsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const TutorialsConfig &config) const = 0;
      virtual void getValue(const TutorialsConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T TutorialsConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T TutorialsConfig::* field;

      virtual void clamp(TutorialsConfig &config, const TutorialsConfig &max, const TutorialsConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const TutorialsConfig &config1, const TutorialsConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, TutorialsConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const TutorialsConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, TutorialsConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const TutorialsConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const TutorialsConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, TutorialsConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, TutorialsConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<TutorialsConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(TutorialsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("controller_type"==(*_i)->name){controller_type = boost::any_cast<int>(val);}
      }
    }

    int controller_type;

    bool state;
    std::string name;

    class REFERENCE_SIGNAL_PARAMETERS
{
  public:
    REFERENCE_SIGNAL_PARAMETERS()
    {
      state = true;
      name = "Reference_Signal_Parameters";
    }

    void setParams(TutorialsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("reference_type"==(*_i)->name){reference_type = boost::any_cast<int>(val);}
        if("ref_angle"==(*_i)->name){ref_angle = boost::any_cast<double>(val);}
        if("sin_ref_gain"==(*_i)->name){sin_ref_gain = boost::any_cast<double>(val);}
        if("sin_ref_f"==(*_i)->name){sin_ref_f = boost::any_cast<double>(val);}
      }
    }

    int reference_type;
double ref_angle;
double sin_ref_gain;
double sin_ref_f;

    bool state;
    std::string name;

    
}reference_signal_parameters;

class STEADY-STATE_TRACKING_CONTROLLER_PARAMETERS
{
  public:
    STEADY-STATE_TRACKING_CONTROLLER_PARAMETERS()
    {
      state = true;
      name = "Steady-State_Tracking_Controller_Parameters";
    }

    void setParams(TutorialsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("ss_Kp"==(*_i)->name){ss_Kp = boost::any_cast<double>(val);}
        if("ss_Ki"==(*_i)->name){ss_Ki = boost::any_cast<double>(val);}
        if("ss_Kd"==(*_i)->name){ss_Kd = boost::any_cast<double>(val);}
      }
    }

    double ss_Kp;
double ss_Ki;
double ss_Kd;

    bool state;
    std::string name;

    
}steady-state_tracking_controller_parameters;

class TRAJECTORY_TRACKING_CONTROLLER_PARAMETERS
{
  public:
    TRAJECTORY_TRACKING_CONTROLLER_PARAMETERS()
    {
      state = true;
      name = "Trajectory_Tracking_Controller_Parameters";
    }

    void setParams(TutorialsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("tr_Kp"==(*_i)->name){tr_Kp = boost::any_cast<double>(val);}
        if("tr_Ki"==(*_i)->name){tr_Ki = boost::any_cast<double>(val);}
        if("tr_Kd"==(*_i)->name){tr_Kd = boost::any_cast<double>(val);}
      }
    }

    double tr_Kp;
double tr_Ki;
double tr_Kd;

    bool state;
    std::string name;

    
}trajectory_tracking_controller_parameters;

}groups;



//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int controller_type;
//#line 15 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      int reference_type;
//#line 17 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      double ref_angle;
//#line 18 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      double sin_ref_gain;
//#line 19 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      double sin_ref_f;
//#line 29 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      double ss_Kp;
//#line 30 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      double ss_Ki;
//#line 31 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      double ss_Kd;
//#line 34 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      double tr_Kp;
//#line 35 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      double tr_Ki;
//#line 36 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      double tr_Kd;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("TutorialsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const TutorialsConfig &__max__ = __getMax__();
      const TutorialsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const TutorialsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const TutorialsConfig &__getDefault__();
    static const TutorialsConfig &__getMax__();
    static const TutorialsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const TutorialsConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void TutorialsConfig::ParamDescription<std::string>::clamp(TutorialsConfig &config, const TutorialsConfig &max, const TutorialsConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class TutorialsConfigStatics
  {
    friend class TutorialsConfig;

    TutorialsConfigStatics()
    {
TutorialsConfig::GroupDescription<TutorialsConfig::DEFAULT, TutorialsConfig> Default("Default", "", 0, 0, true, &TutorialsConfig::groups);
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.controller_type = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.controller_type = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.controller_type = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TutorialsConfig::AbstractParamDescriptionConstPtr(new TutorialsConfig::ParamDescription<int>("controller_type", "int", 0, "A controller type parameter which is edited via an enum", "{'enum': [{'name': 'Steady_State_Tracking', 'type': 'int', 'value': 0, 'srcline': 22, 'srcfile': '/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg', 'description': 'Steady-State Tracking', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'Trajectory_Tracking', 'type': 'int', 'value': 1, 'srcline': 23, 'srcfile': '/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg', 'description': 'Trajectory Tracking', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'An enum to set controller type'}", &TutorialsConfig::controller_type)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TutorialsConfig::AbstractParamDescriptionConstPtr(new TutorialsConfig::ParamDescription<int>("controller_type", "int", 0, "A controller type parameter which is edited via an enum", "{'enum': [{'name': 'Steady_State_Tracking', 'type': 'int', 'value': 0, 'srcline': 22, 'srcfile': '/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg', 'description': 'Steady-State Tracking', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'Trajectory_Tracking', 'type': 'int', 'value': 1, 'srcline': 23, 'srcfile': '/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg', 'description': 'Trajectory Tracking', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'An enum to set controller type'}", &TutorialsConfig::controller_type)));
TutorialsConfig::GroupDescription<TutorialsConfig::DEFAULT::REFERENCE_SIGNAL_PARAMETERS, TutorialsConfig::DEFAULT> Reference_Signal_Parameters("Reference_Signal_Parameters", "", 0, 1, true, &TutorialsConfig::DEFAULT::reference_signal_parameters);
//#line 15 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __min__.reference_type = 0;
//#line 15 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __max__.reference_type = 1;
//#line 15 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __default__.reference_type = 0;
//#line 15 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      Reference_Signal_Parameters.abstract_parameters.push_back(TutorialsConfig::AbstractParamDescriptionConstPtr(new TutorialsConfig::ParamDescription<int>("reference_type", "int", 0, "A reference type parameter which is edited via an enum", "{'enum': [{'name': 'step_like_reference', 'type': 'int', 'value': 0, 'srcline': 11, 'srcfile': '/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg', 'description': 'Step Like Reference', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'trajectory_reference', 'type': 'int', 'value': 1, 'srcline': 12, 'srcfile': '/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg', 'description': 'Trajectory Reference', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'An enum to set reference type'}", &TutorialsConfig::reference_type)));
//#line 15 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __param_descriptions__.push_back(TutorialsConfig::AbstractParamDescriptionConstPtr(new TutorialsConfig::ParamDescription<int>("reference_type", "int", 0, "A reference type parameter which is edited via an enum", "{'enum': [{'name': 'step_like_reference', 'type': 'int', 'value': 0, 'srcline': 11, 'srcfile': '/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg', 'description': 'Step Like Reference', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'trajectory_reference', 'type': 'int', 'value': 1, 'srcline': 12, 'srcfile': '/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg', 'description': 'Trajectory Reference', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'An enum to set reference type'}", &TutorialsConfig::reference_type)));
//#line 17 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __min__.ref_angle = -90.0;
//#line 17 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __max__.ref_angle = 90.0;
//#line 17 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __default__.ref_angle = 0.0;
//#line 17 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      Reference_Signal_Parameters.abstract_parameters.push_back(TutorialsConfig::AbstractParamDescriptionConstPtr(new TutorialsConfig::ParamDescription<double>("ref_angle", "double", 0, "Step-Like Reference Angle", "", &TutorialsConfig::ref_angle)));
//#line 17 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __param_descriptions__.push_back(TutorialsConfig::AbstractParamDescriptionConstPtr(new TutorialsConfig::ParamDescription<double>("ref_angle", "double", 0, "Step-Like Reference Angle", "", &TutorialsConfig::ref_angle)));
//#line 18 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __min__.sin_ref_gain = 0.0;
//#line 18 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __max__.sin_ref_gain = 90.0;
//#line 18 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __default__.sin_ref_gain = 30.0;
//#line 18 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      Reference_Signal_Parameters.abstract_parameters.push_back(TutorialsConfig::AbstractParamDescriptionConstPtr(new TutorialsConfig::ParamDescription<double>("sin_ref_gain", "double", 0, "Sinusoidal Reference Gain", "", &TutorialsConfig::sin_ref_gain)));
//#line 18 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __param_descriptions__.push_back(TutorialsConfig::AbstractParamDescriptionConstPtr(new TutorialsConfig::ParamDescription<double>("sin_ref_gain", "double", 0, "Sinusoidal Reference Gain", "", &TutorialsConfig::sin_ref_gain)));
//#line 19 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __min__.sin_ref_f = 0.0;
//#line 19 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __max__.sin_ref_f = 1.0;
//#line 19 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __default__.sin_ref_f = 0.2;
//#line 19 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      Reference_Signal_Parameters.abstract_parameters.push_back(TutorialsConfig::AbstractParamDescriptionConstPtr(new TutorialsConfig::ParamDescription<double>("sin_ref_f", "double", 0, "Sinusoidal Reference Frequency", "", &TutorialsConfig::sin_ref_f)));
//#line 19 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __param_descriptions__.push_back(TutorialsConfig::AbstractParamDescriptionConstPtr(new TutorialsConfig::ParamDescription<double>("sin_ref_f", "double", 0, "Sinusoidal Reference Frequency", "", &TutorialsConfig::sin_ref_f)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Reference_Signal_Parameters.convertParams();
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(TutorialsConfig::AbstractGroupDescriptionConstPtr(new TutorialsConfig::GroupDescription<TutorialsConfig::DEFAULT::REFERENCE_SIGNAL_PARAMETERS, TutorialsConfig::DEFAULT>(Reference_Signal_Parameters)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(TutorialsConfig::AbstractGroupDescriptionConstPtr(new TutorialsConfig::GroupDescription<TutorialsConfig::DEFAULT::REFERENCE_SIGNAL_PARAMETERS, TutorialsConfig::DEFAULT>(Reference_Signal_Parameters)));
TutorialsConfig::GroupDescription<TutorialsConfig::DEFAULT::STEADY-STATE_TRACKING_CONTROLLER_PARAMETERS, TutorialsConfig::DEFAULT> Steady-State_Tracking_Controller_Parameters("Steady-State_Tracking_Controller_Parameters", "", 0, 2, true, &TutorialsConfig::DEFAULT::steady-state_tracking_controller_parameters);
//#line 29 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __min__.ss_Kp = 0.0;
//#line 29 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __max__.ss_Kp = 50.0;
//#line 29 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __default__.ss_Kp = 37.5;
//#line 29 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      Steady-State_Tracking_Controller_Parameters.abstract_parameters.push_back(TutorialsConfig::AbstractParamDescriptionConstPtr(new TutorialsConfig::ParamDescription<double>("ss_Kp", "double", 0, "Steady-State Kp", "", &TutorialsConfig::ss_Kp)));
//#line 29 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __param_descriptions__.push_back(TutorialsConfig::AbstractParamDescriptionConstPtr(new TutorialsConfig::ParamDescription<double>("ss_Kp", "double", 0, "Steady-State Kp", "", &TutorialsConfig::ss_Kp)));
//#line 30 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __min__.ss_Ki = 0.0;
//#line 30 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __max__.ss_Ki = 10.0;
//#line 30 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __default__.ss_Ki = 0.0;
//#line 30 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      Steady-State_Tracking_Controller_Parameters.abstract_parameters.push_back(TutorialsConfig::AbstractParamDescriptionConstPtr(new TutorialsConfig::ParamDescription<double>("ss_Ki", "double", 0, "Trajectory Tracking Ki", "", &TutorialsConfig::ss_Ki)));
//#line 30 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __param_descriptions__.push_back(TutorialsConfig::AbstractParamDescriptionConstPtr(new TutorialsConfig::ParamDescription<double>("ss_Ki", "double", 0, "Trajectory Tracking Ki", "", &TutorialsConfig::ss_Ki)));
//#line 31 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __min__.ss_Kd = 0.0;
//#line 31 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __max__.ss_Kd = 10.0;
//#line 31 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __default__.ss_Kd = 2.8;
//#line 31 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      Steady-State_Tracking_Controller_Parameters.abstract_parameters.push_back(TutorialsConfig::AbstractParamDescriptionConstPtr(new TutorialsConfig::ParamDescription<double>("ss_Kd", "double", 0, "Trajectory Tracking Kd", "", &TutorialsConfig::ss_Kd)));
//#line 31 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __param_descriptions__.push_back(TutorialsConfig::AbstractParamDescriptionConstPtr(new TutorialsConfig::ParamDescription<double>("ss_Kd", "double", 0, "Trajectory Tracking Kd", "", &TutorialsConfig::ss_Kd)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Steady-State_Tracking_Controller_Parameters.convertParams();
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(TutorialsConfig::AbstractGroupDescriptionConstPtr(new TutorialsConfig::GroupDescription<TutorialsConfig::DEFAULT::STEADY-STATE_TRACKING_CONTROLLER_PARAMETERS, TutorialsConfig::DEFAULT>(Steady-State_Tracking_Controller_Parameters)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(TutorialsConfig::AbstractGroupDescriptionConstPtr(new TutorialsConfig::GroupDescription<TutorialsConfig::DEFAULT::STEADY-STATE_TRACKING_CONTROLLER_PARAMETERS, TutorialsConfig::DEFAULT>(Steady-State_Tracking_Controller_Parameters)));
TutorialsConfig::GroupDescription<TutorialsConfig::DEFAULT::TRAJECTORY_TRACKING_CONTROLLER_PARAMETERS, TutorialsConfig::DEFAULT> Trajectory_Tracking_Controller_Parameters("Trajectory_Tracking_Controller_Parameters", "", 0, 3, true, &TutorialsConfig::DEFAULT::trajectory_tracking_controller_parameters);
//#line 34 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __min__.tr_Kp = 0.0;
//#line 34 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __max__.tr_Kp = 50.0;
//#line 34 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __default__.tr_Kp = 28.5;
//#line 34 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      Trajectory_Tracking_Controller_Parameters.abstract_parameters.push_back(TutorialsConfig::AbstractParamDescriptionConstPtr(new TutorialsConfig::ParamDescription<double>("tr_Kp", "double", 1, "Trajectory Tracking Kp", "", &TutorialsConfig::tr_Kp)));
//#line 34 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __param_descriptions__.push_back(TutorialsConfig::AbstractParamDescriptionConstPtr(new TutorialsConfig::ParamDescription<double>("tr_Kp", "double", 1, "Trajectory Tracking Kp", "", &TutorialsConfig::tr_Kp)));
//#line 35 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __min__.tr_Ki = 0.0;
//#line 35 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __max__.tr_Ki = 10.0;
//#line 35 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __default__.tr_Ki = 0.3;
//#line 35 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      Trajectory_Tracking_Controller_Parameters.abstract_parameters.push_back(TutorialsConfig::AbstractParamDescriptionConstPtr(new TutorialsConfig::ParamDescription<double>("tr_Ki", "double", 1, "Trajectory Tracking Ki", "", &TutorialsConfig::tr_Ki)));
//#line 35 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __param_descriptions__.push_back(TutorialsConfig::AbstractParamDescriptionConstPtr(new TutorialsConfig::ParamDescription<double>("tr_Ki", "double", 1, "Trajectory Tracking Ki", "", &TutorialsConfig::tr_Ki)));
//#line 36 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __min__.tr_Kd = 0.0;
//#line 36 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __max__.tr_Kd = 10.0;
//#line 36 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __default__.tr_Kd = 1.3;
//#line 36 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      Trajectory_Tracking_Controller_Parameters.abstract_parameters.push_back(TutorialsConfig::AbstractParamDescriptionConstPtr(new TutorialsConfig::ParamDescription<double>("tr_Kd", "double", 1, "Trajectory Tracking Kd", "", &TutorialsConfig::tr_Kd)));
//#line 36 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      __param_descriptions__.push_back(TutorialsConfig::AbstractParamDescriptionConstPtr(new TutorialsConfig::ParamDescription<double>("tr_Kd", "double", 1, "Trajectory Tracking Kd", "", &TutorialsConfig::tr_Kd)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Trajectory_Tracking_Controller_Parameters.convertParams();
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(TutorialsConfig::AbstractGroupDescriptionConstPtr(new TutorialsConfig::GroupDescription<TutorialsConfig::DEFAULT::TRAJECTORY_TRACKING_CONTROLLER_PARAMETERS, TutorialsConfig::DEFAULT>(Trajectory_Tracking_Controller_Parameters)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(TutorialsConfig::AbstractGroupDescriptionConstPtr(new TutorialsConfig::GroupDescription<TutorialsConfig::DEFAULT::TRAJECTORY_TRACKING_CONTROLLER_PARAMETERS, TutorialsConfig::DEFAULT>(Trajectory_Tracking_Controller_Parameters)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(TutorialsConfig::AbstractGroupDescriptionConstPtr(new TutorialsConfig::GroupDescription<TutorialsConfig::DEFAULT, TutorialsConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<TutorialsConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<TutorialsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<TutorialsConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    TutorialsConfig __max__;
    TutorialsConfig __min__;
    TutorialsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const TutorialsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static TutorialsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &TutorialsConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const TutorialsConfig &TutorialsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const TutorialsConfig &TutorialsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const TutorialsConfig &TutorialsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<TutorialsConfig::AbstractParamDescriptionConstPtr> &TutorialsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<TutorialsConfig::AbstractGroupDescriptionConstPtr> &TutorialsConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const TutorialsConfigStatics *TutorialsConfig::__get_statics__()
  {
    const static TutorialsConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = TutorialsConfigStatics::get_instance();

    return statics;
  }

//#line 11 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      const int Tutorials_step_like_reference = 0;
//#line 12 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      const int Tutorials_trajectory_reference = 1;
//#line 22 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      const int Tutorials_Steady_State_Tracking = 0;
//#line 23 "/home/oguz/robot-control/hw2/robot-control/src/dynamic_parameters/cfg/Tutorials.cfg"
      const int Tutorials_Trajectory_Tracking = 1;
}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __TUTORIALSRECONFIGURATOR_H__
